config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get "about" => "static_pages#about"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'users/:id'   => 'users#getpass', as: "derivepass"
  post   'refresh_salt'  => 'sites#refresh_salt'
  get   'activation_email' => 'users#request_activation_email'
  delete 'logout'  => 'sessions#destroy'
  get 'sesions/new'
  get "signup" => 'users#new'
  post "changelocale" => "static_pages#change_locale"
  root "static_pages#home"

  resources :users
  resources :sites
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include SessionsHelper
	include ApplicationHelper

  def home
  	logger.debug "-----> Logged in?: #{logged_in?}"
  	if logged_in?
  		redirect_to current_user
  	end
  end

	def change_locale
		if params.include? :locale 
			cookies.permanent[:locale] = params[:locale]
		end
		redirect_to root_path
	end

	def home
		if logged_in?
			redirect_to current_user
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, t(".title")) %>

<h2 class="text-primary" style="margin-top:30px;margin-bottom:20px"> <%= t ".text_title_html" %> </h2>


<p> <%= t ".text_first_paragraph" %> </p>

<p> <%= t ".text_second_paragraph_html", rails_link: link_to(t(".rails"),"http://rubyonrails.org/", target: "_blank") %> </p>
<ul>
	<li>
		<h3> <%= t ".what_is_title" %> </h3>
		<p> <%= t ".what_is_text" %></p>
	</li>
	<li>
		<h3> <%= t ".text_second_title" %> </h3>
		<p> <%= t ".text_stored" %></p>
	</li>
	<li>
		<h3> <%= t ".text_third_title" %> </h3>
		<p> <%= t ".text_work" %></p>
	</li>
	<li>
		<h3> <%= t ".text_four_title" %> </h3>
		<p> <%= t ".text_trust_html", bitbucket: link_to(t(".bitbucket"),"https://bitbucket.org/jparaque/passlist", target: "_blank") %></p>
	</li>
</ul>

<div class="row">
<div class="col-md-8 col-lg-8 col-sm-8" style="padding-top:20px;padding-left:10px">
	<p><h2> <%= t ".goodbye_html" %></h2></p>
</div>

<div class="col-md-4 col-lg-4 col-sm-4 well" style="padding-top:10px;padding-bottom:15px">

		<div class="container" style="border-bottom-width:1px;margin-bottom:0px">
		<h4><b><%= t ".contact_me" %></b></h4>
		</div>

		<div class="col-md-4 col-lg-4 col-sm-4">
			<%= link_to image_tag("gplus.png" ,style: "width:100%"), "http://plus.google.com/+JuanpeAraque", target: "_blank", class: "circle" %>
		</div>
		<div class="col-md-4 col-lg-4 col-sm-4">
			<%= link_to image_tag("twitter.png" ,style: "width:100%"), "http://twitter.com/AAraKKe", target: "_blank", class: "circle contact-logo"  %>
		</div>
		<div class="col-md-4 col-lg-4 col-sm-4">
			<%= link_to image_tag("telegram.png" ,style: "width:100%"), "http://telegram.me/Juanpe", target: "_blank", class: "circle contact-logo"  %>
		</div>

</div>
</div>

app/views/static_pages/home.html.erb
<%= render partial: "layouts/flashes"  %>

<div class="center jumbotron" style="margin-top:50px">

  <h1><%= t ".title" %></h1>
  <h2>
   <%= t ".description" %>
  </h2>

  <%= link_to t("sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
</div>

<div class="col-md-3 col-sm-4 col-lg-4">
<h2><%= t(".list_one.title") %></h2><br/>
<div class="list-group">
    <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-content-create"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_one.first.title") %> </h4>
            <p class="list-group-item-text"> <%= t(".list_one.first.text") %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
        <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-content-add-circle-outline"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_one.second.title") %> </h4>
            <p class="list-group-item-text"> <%= t(".list_one.second.text") %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
        <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-action-lock-outline"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_one.third.title") %> </h4>
            <p class="list-group-item-text"> <%= t(".list_one.third.text") %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
</div>
</div>

<div class="col-md-5 col-sm-5 col-lg-5">
<h2><%= t(".list_two.title") %></h2><br/>
<div class="list-group">
    <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-alert-warning"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_two.first.title") %> </h4>
            <p class="list-group-item-text"> <%= t(".list_two.first.text") %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
        <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-image-looks-one"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_two.second.title") %> </h4>
            <p class="list-group-item-text"> <%= t(".list_two.second.text") %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
        <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-editor-format-list-bulleted"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_two.third.title") %> </h4>
            <p class="list-group-item-text"> <%= t(".list_two.third.text") %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
</div>
</div>

<div class="col-md-3 col-sm-3 col-lg-3">
<h2><%= t(".list_three.title") %></h2><br/>
<div class="list-group">
        <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-social-person-outline"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_three.first.title") %> </h4>
            <p class="list-group-item-text"> <%= link_to t(".list_three.first.text"), about_path %></p>
        </div>
    </div>

    <div class="list-group-separator"></div>
    <div class="list-group-item">
        <div class="row-action-primary">
            <i class="mdi-action-launch"></i>
        </div>
        <div class="row-content">
            <div class="action-secondary"></div>
            <h4 class="list-group-item-heading"><%= t(".list_three.second.title") %> </h4>
            <p class="list-group-item-text"> <%= link_to t(".list_three.second.text"), "https://bitbucket.org/jparaque/passlist", target: "_blank" %></p>
        </div>
    </div>
    <div class="list-group-separator"></div>
</div>
</div>