config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get "about" => "static_pages#about"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'users/:id'   => 'users#getpass', as: "derivepass"
  post   'refresh_salt'  => 'sites#refresh_salt'
  get   'activation_email' => 'users#request_activation_email'
  delete 'logout'  => 'sessions#destroy'
  get 'sesions/new'
  get "signup" => 'users#new'
  post "changelocale" => "static_pages#change_locale"
  root "static_pages#home"

  resources :users
  resources :sites
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	include SessionsHelper
	before_action :get_user, only: [:edit,:update]
	before_action :valid_user, only: [:edit,:update]
	before_action :check_expiration, only: [:edit,:update]

	def new
	end

	def edit
	end

	def create
		@user = User.find_by(email: params[:password_reset][:email].downcase)
		if @user 
			@user.create_reset_digest
			@user.send_password_reset_email
			flash[:info] = t ".flash_info"
			redirect_to root_url
		else
			flash[:danger] = t ".flash_danger"
			redirect_to root_url
		end
	end

	def update
		if password_blank?
			flash.now[:danger] = (".flash_danger")
			render "edit"
		elsif @user.update_attributes(user_params)
			log_in @user
			@user.update_attribute(:reset_digest, User.digest(User.new_token))
			flash[:success] = t(".flash_success")
			redirect_to @user
		else
			render "edit"
		end
	end

	private
	def user_params
		params.require(:user).permit(:password, :password_confirmation)
	end

	def get_user
		@user = User.find_by(email: params[:email])
	end

	def valid_user
		unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
			redirect_to root_url
		end
	end 

	def check_expiration
		if @user.password_reset_expired?
			flash[:danger] = t(".flash_danger")
			redirect_to new_password_reset_url
		end
	end

	def password_blank?
		params[:user][:password].blank?
	end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, t(".title")) %>


<div class="col-md-6 center-signup col-md-offset-3 well bs-component">
<% if @user.errors.any? %>
<div class="alert alert-danger">
	<strong><%= t(:snap) %> </strong> <%= t(:no_edit_accout_error) %>
</div>
<%end%>
	<%= form_for(@user, url: password_reset_path(params[:id]), html: {class: "form-horizontal"}) do |f| %>
	<legend><%= t(".form_legend") %></legend>
	<fieldset>
		<%= hidden_field_tag :email, @user.email %>
		<div class= "form-group <%= get_form_group_cl @user.errors,:password %>">
			<div class="col-lg-7">
				<%= f.password_field :password, class: "form-control floating-label", placeholder: "#{get_form_ph @user.errors, :password,t(:password)}" %>
			</div>
		</div>


		<div class="form-group <%= get_form_group_cl @user.errors,:password_confirmation %>">
			<div class="col-lg-7">
				<%= f.password_field :password_confirmation, class: "form-control", placeholder: "#{get_form_ph @user.errors, :password_confirmation, t(:pass_confirm)}" %>
			</div>

		</div>
	</fieldset>
	<row>
		<%= link_to t(:cancel), root_url, class: "btn btn-flat btn-default" %>
		<%= f.submit t(".submmit"), class: "btn btn-primary" %>
	</row>
	<% end %>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, t(".title")) %>


<div class="col-md-6 col-lg-6 col-sm-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3 well bs-component" style="margin-top:50px">
<p style="text-align:left"> <%= t ".explanation" %></p><br/>

	<%= form_for(:password_reset, url: password_resets_path, html: {class: "form-horizontal"}) do |f| %>
	<legend> <%= t(".form_legend") %></legend>
	<fieldset>

		<div class="form-group">
			<div class="col-lg-10 col-md-10">
				<%= f.email_field :email, class: "form-control", placeholder: t(:email)  %>
			</div>
		</div>

	</fieldset>
	<row>
		<%= link_to t(:cancel), root_path, class: "btn btn-flat btn-default" %>
		<%= f.submit t(".submmit"), class: "btn btn-primary"%>
	</row>
	<% end %>

</div>