config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get "about" => "static_pages#about"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'users/:id'   => 'users#getpass', as: "derivepass"
  post   'refresh_salt'  => 'sites#refresh_salt'
  get   'activation_email' => 'users#request_activation_email'
  delete 'logout'  => 'sessions#destroy'
  get 'sesions/new'
  get "signup" => 'users#new'
  post "changelocale" => "static_pages#change_locale"
  root "static_pages#home"

  resources :users
  resources :sites
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/models/user.rb
require "valid_email"
require "bcrypt"

class User < ActiveRecord::Base
	attr_accessor :remember_token, :activation_token, :reset_token

	validates :name, presence: true
	validates :email, presence: true, confirmation: true,
		email: true, uniqueness: {case_sensitive: false}
	validates :password, length: {minimum: 8}, allow_blank: true
	has_many :sites
	before_save :downcase_email
	before_create :create_activation_digest
	has_secure_password

	def self.new_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest,nil)
	end

	# Returns true if the given token matches the digest.
  	def authenticated?(digest,token)
  		#valid = BCrypt::Password.new(remember_digest).is_password?(remember_token)
  		#logger.debug "Valid token: #{valid}"
  		digest = self.send("#{digest}_digest")
    	result = digest ? BCrypt::Password.new(digest).is_password?(token) : false
  	end

  	def create_activation_digest
  		if !self.activated
  			self.activation_token = User.new_token
  			self.activation_digest = User.digest(activation_token)
  		end
  	end

  	def create_reset_digest
  		self.reset_token = User.new_token
  		update_attribute(:reset_digest, User.digest(reset_token))
  		update_attribute(:reset_sent_at, Time.zone.now)
  	end

  	 def send_password_reset_email
    	UserMailer.password_reset(self).deliver_now
  	end

  	def password_reset_expired?
  		reset_sent_at < 2.hours.ago
  	end

  	private

  	def downcase_email
  		self.email = email.downcase
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper
	include ApplicationHelper
	require 'digest/sha1'

	before_action :correct_user, only: [:show,:edit,:update]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			I18n.locale = user_params[:locale].to_sym
			request_activation_email
			flash[:info] = t(".info")
			log_in @user
			redirect_to @user
		else 
			render "new"
		end
	end

	def show
		@user = User.find(params[:id])
		respond_to do |format|
			format.html
			format.js
		end
	end

	def getpass
		@user = current_user
		params[:pass_hash] = Digest::SHA1.hexdigest(params[:pass].to_s)
		params.delete(:pass)
		render "show"
	end

	def edit
		@user = correct_user
	end

	def update
		@user = correct_user
		if @user.update_attributes(user_params)
			I18n.locale = user_params[:locale].to_sym
			flash[:success] = t(".success")
			redirect_to @user
		else
			render "edit"
		end
	end

	def request_activation_email(redirect=false)
		user = @user ? @user : nil
		if params[:redirect] || redirect
			user = current_user
			user.create_activation_digest 
			user.save
		end
		UserMailer.account_activation(user).deliver_now
		if params[:redirect] || redirect
			flash[:info] = t(".flash_send")
			redirect_to user
		end
	end

	private 

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation,:locale)
	end

	def correct_user
		@user = User.find_by(id: params[:id])
		redirect_to root_path unless @user == current_user && @user
		@user
	end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_sitelist.html.erb
<div class="row">
	<% user.sites.order(:id).each_with_index do |site,i| %>
	<% if i%3 == 0 && i != 0 %>
</div><div class="row">
<% end %>
<div class="col-md-4">
	<div class="bs-container">
		<div class="panel panel-default">
			<div class="panel-heading" style="padding-top:5px;padding-bottom:5px">
				<h3 style="margin-top: 0px;margin-bottom: 0px;"><strong><%= site.site %></strong></h3>
			</div>
			<div class="panel-body" style="padding-bottom:3px;padding-top:3px">
			<div class="row" style="padding-bottom:2px;padding-right:2px;padding-left:2px;padding-top:2px">
				<div class="col-md-12 col-lg-12">
					<h6><%= "#{site.nchar} #{t(".characters")}" %> </h6>
					<% pass_to_show = site.generate_pass(pass)  %>
					<% if !pass_to_show.empty? %>
					<p><strong> <%= t(:password) %>:</strong></p>
					<h5> <%= pass_to_show %></h5>
					<% end %>
					<%#= button_to "",{controller: "sites", action: "copy_to_cp", data: {site_pass: site.generate_pass(pass)}}, class: "btn btn-fab btn-raised btn-add mdi-content-content-copy " %>
				</div>
			</div>
			<div class="row" style="margin-bottom: 0px;">
				<div class="col-md-8 col-md-offset-4" style="padding-right: 10px;padding-bottom: 10px;">
					<div class="btn-group" style="float:right;float:bottom;margin-bottom: 0px;">
						<%= link_to "",{controller: "sites", action: "refresh_salt", data: {id: site.id,pass: pass}}, method: "post", class: "btn btn-default mdi-navigation-refresh site-card-btns", style: "padding-left: 10px;font-size:20px;"%>
						<%= link_to "",edit_site_path(site,site: {user_id: @user.id}), class: "btn btn-default mdi-editor-mode-edit site-card-btns", style: "padding-left: 10px;font-size:20px;" %>
						<%= link_to "",site, method: "delete", class: "btn btn-default mdi-action-delete btn-alert site-card-btns", style: "padding-left: 10px;font-size:20px;" %>
					</div>
				</div>
			</div>
			</div>
		</div>
	</div>
</div>
<%end%>
</div>

app/views/users/_user_card.html.erb
<div class="col-md-4 user-card">
	<h1> <%= user_card.name.humanize %> </h1>
	<h4> <%= t(".sites_stored")+": "+user_card.sites.count.to_s %> </h4>
</div>

app/views/users/edit.html.erb
<% provide(:title, t(".title")) %>


<div class="col-md-6 center-signup col-md-offset-3 well bs-component">
<% if @user.errors.any? %>
<div class="alert alert-danger" style="text-align:left">
	<%= t(".errors_html") %>
	<ul>
		<% @user.errors.messages.each do |k,msg| %>
      		<li><%= msg[0] %></li>
    	<% end %>
    </ul>
</div>
<%end%>
	<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
	<legend><%= t(".legend") %></legend>
	<fieldset>
		<div class="form-group <%= get_form_group_cl @user.errors,:name %>">
			<div class="col-lg-10">
				<%= f.text_field :name, class: "form-control", placeholder: "#{get_form_ph @user.errors, :name}" %>
			</div>
		</div>

		<div class="form-group <%= get_form_group_cl @user.errors,:email %>">
			<div class="col-lg-10">
				<%= f.email_field :email, class: "form-control", placeholder: "#{get_form_ph @user.errors, :email}"  %>
			</div>

		</div>

		<div class= "form-group <%= get_form_group_cl @user.errors,:password %>">
			<div class="col-lg-7">
				<%= f.password_field :password, class: "form-control floating-label", placeholder: "#{get_form_ph @user.errors, :password,t(:password)}" %>
			</div>
		</div>


		<div class="form-group <%= get_form_group_cl @user.errors,:password_confirmation %>">
			<div class="col-lg-7">
				<%= f.password_field :password_confirmation, class: "form-control", placeholder: "#{get_form_ph @user.errors, :password_confirmation, t(:pass_confirm)}" %>
			</div>

		</div>

			<div class="form-group <%= get_form_group_cl @user.errors,:locale %>">
			<%= f.label :locale, t(:language), class: "col-lg-2 control-label" %>
			<div class="col-md-3 col-lg-3 col-sm-3">
				<%= f.select :locale,get_languages_list, {}, class: "form-control", placeholder: "#{get_form_ph @user.errors, :locale}" %>
			</div>

		</div>
	</fieldset>
	<row>
		<%= link_to t(:cancel), @user, class: "btn btn-flat btn-default" %>
		<%= f.submit t(".submmit"), class: "btn btn-primary" %>
	</row>
	<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, t(".title")) %>


<div class="col-md-6 center-signup col-md-offset-3 well bs-component">
<% if @user.errors.any? %>
<div class="alert alert-danger" style="text-align:left">
	<%= t(".errors_html") %>
	<ul>
		<% @user.errors.messages.each do |k,msg| %>
      		<li><%= msg[0] %></li>
    	<% end %>
    </ul>
</div>
<%end%>
	<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
	<legend><%= t(".legend") %></legend>
	<fieldset>
		<div class="form-group <%= get_form_group_cl @user.errors,:name %>">
			<div class="col-lg-10">
				<%= f.text_field :name, class: "form-control", placeholder: "#{get_form_ph @user.errors, :name}" %>
			</div>
		</div>

		<div class="form-group <%= get_form_group_cl @user.errors,:email %>">
			<div class="col-lg-10">
				<%= f.email_field :email, class: "form-control", placeholder: "#{get_form_ph @user.errors, :email}"  %>
			</div>

		</div>

		<div class= "form-group <%= get_form_group_cl @user.errors,:password %>">
			<div class="col-lg-7">
				<%= f.password_field :password, class: "form-control floating-label", placeholder: "#{get_form_ph @user.errors, :password, t(:password)}" %>
			</div>
		</div>


		<div class="form-group <%= get_form_group_cl @user.errors,:password_confirmation %>">
			<div class="col-lg-7">
				<%= f.password_field :password_confirmation, class: "form-control", placeholder: "#{get_form_ph @user.errors, :password_confirmation, t(:pass_confirm)}" %>
			</div>

		</div>

			<div class="form-group <%= get_form_group_cl @user.errors,:locale %>">
			<%= f.label :locale, t(:language), class: "col-lg-2 control-label" %>
			<div class="col-md-3 col-lg-3 col-sm-3">
				<%= f.select :locale,get_languages_list, {}, class: "form-control", placeholder: "#{get_form_ph @user.errors, :locale}" %>
			</div>

		</div>
	</fieldset>
	<row>
		<%= link_to t(:cancel), root_path, class: "btn btn-flat btn-default" %>
		<%= f.submit t(".submmit"), class: "btn btn-primary" %>
	</row>
	<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<%= render partial: "layouts/flashes" %>
<div class="bs-container cold-md-12" style="margin-top:30px">
<div class="well">
<div class="row">
<%= render partial: "users/user_card", object: @user %> 
<div class="col-md-3 master-pass">
<%= form_tag({controller: "users", action: "getpass"}, class: "form-horizontal") %>
<%= password_field_tag(:pass, "", required: true, class: "form-control", placeholder: t(".master_password_placeholder")) %>
<%= password_field_tag(:id, @user.id, class: "hidden") %>
<%= submit_tag( t(".gen_passwords_button") ,class: "btn btn-primary btn-xs mdi-action-autorenew") %>
</div>
</div>

<div class="row">
<div class="col-lg-8">
<h2> <%= get_sites_title(@user.sites.count) %> </h2>
</div>
</div>

<%= render partial: "users/sitelist", locals: {user: @user,pass: params[:pass_hash]} %>


<div class="row">
<%= link_to "", new_site_path(site: {user_id: @user.id}), class: "btn btn-primary btn-fab btn-raised mdi-content-add btn-add", style: "margin-right: 15px;
    border-bottom-width: 15px;
    margin-bottom: 15px;
    border-right-width: 6px;
    margin-top: 15px;" %>
</div>
</div>
</div>