config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get "about" => "static_pages#about"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'users/:id'   => 'users#getpass', as: "derivepass"
  post   'refresh_salt'  => 'sites#refresh_salt'
  get   'activation_email' => 'users#request_activation_email'
  delete 'logout'  => 'sessions#destroy'
  get 'sesions/new'
  get "signup" => 'users#new'
  post "changelocale" => "static_pages#change_locale"
  root "static_pages#home"

  resources :users
  resources :sites
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_flashes.html.erb
<% if !flash.empty? %>
	<% flash.each do |f,text| %>
	<div class="row">
	<div class="col-md-5 col-lg-5 col-sm-5 alert alert-dismissable alert-<%= f %>" style="margin-left:20px;margin-top:20px;margin-bottom:0px;">
    	<button type="button" class="close" data-dismiss="alert">x</button>
    	<p> <%= raw text %> </p>
	</div>
	</div>
	<%end%>
<%end%>

app/views/layouts/_footer.html.erb
<div class="row">
<footer class="footer" style="border-top-width:2px;border-top-color:#009587">
    <div class="container">
      <nav>
      <%= t(".passlist",version: app_version) %>
        <ul>
          <li><%= link_to t("about"), about_path %></li>
          <li><%= link_to t(".bitbucket"), "https://bitbucket.org/jparaque/passlist/src" %></li>
        </ul>
      </nav>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="margin-bottom: 0px;">
  <div class="container">
    <h5 style="margin-bottom: 0px;margin-top: 0px;"><%= link_to "PassList", root_path, id: "logo", class: "mdi-action-lock" %></h5>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if menu.class != Hash %>
        <li><%= link_to t(:about), about_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li> <%= link_to t(".edit_profile"), edit_user_path(current_user) %></li>
            <li> <%= link_to t(".logout"), logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to t(".login"), login_path %></li>
        <li><%= link_to t(:sign_up), new_user_path %></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(".language") %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% get_languages_list.each do |lan| %>
            <li> <%= link_to lan[0], {controller: "static_pages", action: "change_locale", locale: lan[1]}, method: "post" %></li>
            <%end%>
          </ul>
          <% end %>
          <% else %>
          <% menu.each do |name,link| %>
          <li><%= link_to name,link %></li>
          <% end %>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track','jquery-ui' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <meta name="theme-color" content="#005F56">
    <%= render partial: 'layouts/shim' %>
  </head>
  <body>
    <%= render partial: 'layouts/header', locals: {menu: yield(:menu)} %>
    <div class="container">
      <div class="row">
      <%= yield %>
      </div>
      <%= render partial: "layouts/footer" %>
      </div>
      <% if Rails.env.development? %>
      <div class="row col-md-12">
      <%= debug(params) %>
      <div>
      <% end %>
  </body>
</html>